### ISSUE TITLE
[CRASH]  Unhandled .Win32Exception exception when running  ">D2ROffline.exe Game.exe"

### ISSUE THREAD

**Issue by harry-hathorn** [ferib/D2R-Offline#113]
**Describe the crash**
When I run the command" D2ROffline.exe Game.exe" in  the D2R folder I get the following command output and the game does not run:
[21:48:03.58653]: Launching game...
[21:48:03.60118]: Process started...
[21:48:04.70711]: Suspending process...
Unhandled exception. System.ComponentModel.Win32Exception (299): Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at D2ROffline.Program.Main(String[] args)
   
I got a bnet installer  from here barncastle/Battle.Net-Installer and ran "BNetInstaller.exe --prod osib --uid osi_beta --lang enus --dir "C:\D2R"" to download the D2R copy. Is this 32 bit version is that the problem? How can I fix this.   

**Which version did you use?**
I downloaded 1.0.1

**Which patches.txt did you use?**
I am trying to run the game not trying to patch anything.

**Comment by ferib** [comment]
get the latest v2 from release and try again, the "only part of a ReadProcessMemory .." error may be caused due to anti-virus, or any other service, interrupting the tool.

**Comment by harry-hathorn** [comment]
Hey Ferib,
I have tried with the latest 2.0.8. It still suspends the process. Do you have an idea how to fix this? I only have windows defender installed.

I'm not sure if there's something wrong with my D2R download. How do you recommend  downloading the D2R copy? Or are the steps I described previously correct?

Here's the output:
[08:00:14.43872]: Launching game...
[08:00:14.44068]: Extra parameters not found. Proceeding...
[08:00:14.54568]: Process started...
[08:00:14.54768]: Opening process...
[08:00:14.54872]: Waiting for data at 0x7FF6C1D68858...
[08:00:16.63694]: Suspending process...
[08:00:16.63894]: Process suspended
[08:00:16.66019]: Remapping process..
[08:00:16.72824]: Patching 0x7FF6C07DAD68
[08:00:16.72922]: Patching 0x7FF6C07DE25F
[08:00:16.72922]: Patching 0x7FF6C073FB9D
[08:00:16.73020]: Patching 0x7FF6C0027E1C
[08:00:16.73020]: Patching 0x7FF6C06EE81C
[08:00:16.73020]: Patching 0x7FF6C07F15F2
[08:00:16.73120]: Patching 0x7FF6BFE2FC03
[08:00:16.73120]: Patching 0x7FF6BFE2FCB6
[08:00:16.73620]: Bypassed CRC at 7FF6BFB454D0
[08:00:16.73620]: Bypassed CRC at 7FF6BFB47430
[08:00:16.73924]: Bypassed CRC at 7FF6BFBF62B1
[08:00:16.74024]: Bypassed CRC at 7FF6BFC4D901
[08:00:16.77020]: Bypassed CRC at 7FF6C06A58C0
[08:00:16.77120]: Bypassed CRC at 7FF6C06A5DB0
[08:00:16.77220]: Bypassed CRC at 7FF6C06B2251
[08:00:16.77220]: Bypassed CRC at 7FF6C06B28D0
[08:00:16.78977]: Bypassed CRC at 7FF6C0C78111
[08:00:16.79880]: Bypassed CRC at 7FF6C0FAC501
[08:00:16.79977]: Bypassed CRC at 7FF6C0FCCFD1
[08:00:16.80077]: Bypassed CRC at 7FF6C0FDFC71
[08:00:16.80177]: Bypassed CRC at 7FF6C0FF7891
[08:00:16.80177]: Bypassed CRC at 7FF6C0FFF690
[08:00:16.80177]: Bypassed CRC at 7FF6C1005FC0
[08:00:16.80277]: Bypassed CRC at 7FF6C10223A0
[08:00:16.80377]: Bypassed CRC at 7FF6C102D9B1
[08:00:16.80477]: Bypassed CRC at 7FF6C1037DD1
[08:00:16.80477]: Bypassed CRC at 7FF6C1054791
[08:00:16.80577]: Bypassed CRC at 7FF6C107EA30
[08:00:16.80677]: Bypassed CRC at 7FF6C1082D31
[08:00:16.80677]: Bypassed CRC at 7FF6C108FB61
[08:00:16.80873]: Bypassed CRC at 7FF6C10A3930
[08:00:16.80873]: Bypassed CRC at 7FF6C10AC8F1
[08:00:16.80974]: Bypassed CRC at 7FF6C10AE981
[08:00:16.81339]: Bypassed CRC at 7FF6C10C02E0
[08:00:16.81475]: Bypassed CRC at 7FF6C10C42F0
[08:00:16.81574]: Bypassed CRC at 7FF6C10CCAE1
[08:00:16.81674]: Bypassed CRC at 7FF6C10D0771
[08:00:16.81674]: Bypassed CRC at 7FF6C10D3F81
[08:00:16.81775]: Bypassed CRC at 7FF6C10D5D71
[08:00:16.81874]: Bypassed CRC at 7FF6C10EAFF1
[08:00:16.81874]: Bypassed CRC at 7FF6C10F0A50
[08:00:16.81974]: Bypassed CRC at 7FF6C11183B1
[08:00:16.82074]: Bypassed CRC at 7FF6C1128961
[08:00:16.84951]: Resuming process..
[08:00:16.85152]: Done!
[08:00:16.85256]: Press any key to exit...

**Comment by harry-hathorn** [comment]
![image](https://user-images.githubusercontent.com/25703773/115828994-b0f0ca80-a40e-11eb-862f-56e3346cad15.png)

The error is thrown here

stacktrace
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at D2ROffline.Tools.Patcher.Start(String d2rPath, Int32 crashDelay, String d2rargs) in D:\Games\D2R\D2R-Offline-2.0.8\D2R-Offline-2.0.8\src\Tools\Patcher.cs:line 61
   at D2ROffline.Program.HandlerArgs(String[] args) in D:\Games\D2R\D2R-Offline-2.0.8\D2R-Offline-2.0.8\src\Program.cs:line 71
   at D2ROffline.Program.Main(String[] args) in D:\Games\D2R\D2R-Offline-2.0.8\D2R-Offline-2.0.8\src\Program.cs:line 22

**Comment by ferib** [comment]
Duplicates of #2 and #12.
