### ISSUE TITLE
Unhandle exception error

### ISSUE THREAD

**Issue by razsa** [ferib/D2R-Offline#2]
Unhandled exception. System.ComponentModel.Win32Exception (299): Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at D2ROffline.Program.Main(String[] args) in C:\Users\K\Downloads\D2R-Offline\Program.cs:line 50

**Comment by ferib** [comment]
Your game may has exited while the tool tried to patch it.
To make sure everything runs smoothly, kill all `game.exe` processes and launch the tool using admin rights.

**Comment by tgonzalez89** [comment]
I'm having the same issue. No game.exe processes are running and I launched the tool in an admin terminal.

**Comment by DiglettDig777** [comment]
I am having the same issue, checked for game.exe running and I didn't find it.
When I built the file it didn't come out as bin/Debug/dotnetcore3.1/ like it says in the readme but instead bin/Debug/netcoreapp3.1 so not sure if I did something wrong

**Comment by ferib** [comment]
> When I built the file it didn't come out as bin/Debug/dotnetcore3.1/ like it says in the readme but instead bin/Debug/netcoreapp3.1
Might have twisted the words, but that should not matter.
Anyway, the memory access to the process got interrupted somehow, may it be anti-virus, process exit/crash, or something else.

**Comment by AvidExplorer** [comment]
I found some relevant information that may help to debug this.

When ` Process.Start(pInfo);`  is called, the process Game.exe automatically exits after some miliseconds. I think this happens because the Game.exe checks for some config to know if it can run or not, perhaps those who have had access to the game through the official invitation have a Windows Registry key or similar that let's the game continue running.

What I found is that if you change `Thread.Sleep(1100);` to `Thread.Sleep(200);` the patcher works fine in my computer, probably because the game doesn't have enough time to perform those checks mentioned above.

The problem with this is that after applying the patches, the game still crashes with a random error:

![d2error](https://user-images.githubusercontent.com/82579214/114849145-c4cd7880-9ddf-11eb-9ee4-ab551223946b.png)

**Comment by tgonzalez89** [comment]
I tried reducing the delay before it patches and it now says it's done, but the game never launches.

`[09:31:45.49376]: Launching game...
[09:31:45.58939]: Process started...
[09:31:45.90058]: Suspending process...
[09:31:45.91296]: Process suspended
[09:31:45.91327]: Remapping process..
[09:31:45.97801]: Patching base+D4AD68
[09:31:45.97868]: Patching base+D4E25F
[09:31:45.97903]: Patching base+CAFB9D
[09:31:45.97965]: Patching base+597E1C
[09:31:45.98019]: Patching base+C5E81C
[09:31:45.98057]: Patching base+D615F2
[09:31:45.98092]: Patching base+39FC03
[09:31:45.98640]: Bypassed CRC at 7FF6F38254D0
[09:31:45.98694]: Bypassed CRC at 7FF6F3827430
[09:31:45.98881]: Bypassed CRC at 7FF6F3862F50
[09:31:45.98954]: Bypassed CRC at 7FF6F386EE80
[09:31:45.99000]: Bypassed CRC at 7FF6F386F550
[09:31:45.99275]: Bypassed CRC at 7FF6F38D62B1
[09:31:45.99520]: Bypassed CRC at 7FF6F392D901
[09:31:46.05549]: Bypassed CRC at 7FF6F43858C0
[09:31:46.05595]: Bypassed CRC at 7FF6F4385DB0
[09:31:46.05659]: Bypassed CRC at 7FF6F4392251
[09:31:46.05698]: Bypassed CRC at 7FF6F43928D0
[09:31:46.09056]: Bypassed CRC at 7FF6F4958111
[09:31:46.10948]: Bypassed CRC at 7FF6F4C8C501
[09:31:46.11056]: Bypassed CRC at 7FF6F4CACFD1
[09:31:46.11135]: Bypassed CRC at 7FF6F4CBFC71
[09:31:46.11225]: Bypassed CRC at 7FF6F4CD7891
[09:31:46.11281]: Bypassed CRC at 7FF6F4CDF690
[09:31:46.11329]: Bypassed CRC at 7FF6F4CE5FC0
[09:31:46.11427]: Bypassed CRC at 7FF6F4D023A0
[09:31:46.11490]: Bypassed CRC at 7FF6F4D0D9B1
[09:31:46.11548]: Bypassed CRC at 7FF6F4D17DD1
[09:31:46.11828]: Bypassed CRC at 7FF6F4D34791
[09:31:46.11988]: Bypassed CRC at 7FF6F4D5EA30
[09:31:46.12098]: Bypassed CRC at 7FF6F4D62D31
[09:31:46.12268]: Bypassed CRC at 7FF6F4D6FB61
[09:31:46.12467]: Bypassed CRC at 7FF6F4D83930
[09:31:46.12531]: Bypassed CRC at 7FF6F4D8C8F1
[09:31:46.12579]: Bypassed CRC at 7FF6F4D8E981
[09:31:46.12660]: Bypassed CRC at 7FF6F4DA02E0
[09:31:46.12707]: Bypassed CRC at 7FF6F4DA42F0
[09:31:46.12764]: Bypassed CRC at 7FF6F4DACAE1
[09:31:46.12808]: Bypassed CRC at 7FF6F4DB0771
[09:31:46.12838]: Bypassed CRC at 7FF6F4DB3F81
[09:31:46.12864]: Bypassed CRC at 7FF6F4DB5D71
[09:31:46.12936]: Bypassed CRC at 7FF6F4DCAFF1
[09:31:46.12973]: Bypassed CRC at 7FF6F4DD0A50
[09:31:46.13292]: Bypassed CRC at 7FF6F4DF83B1
[09:31:46.13472]: Bypassed CRC at 7FF6F4E08961
[09:31:46.20870]: Resuming process..
[09:31:46.20973]: Done!

**Comment by ferib** [comment]
> I tried reducing the delay before it patches and it now says it's done, but the game never launches.

Hold my beer while I try to solve the timing issue!

**Comment by anta88** [comment]
Same problem here, Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
I have no standalone antivirus, just windows defender which I tried to disable. Any idea?

**Comment by Dankmank** [comment]
I get the same error. Google spit this out, has it anything to do with it?

**"I know that the Only part of a ReadProcessMemory or WriteProcessMemory request was completed exception is thrown when a 32-bit process tries to access a 64-bit process and the same for a 64-bit modifying a 32-bit process.

The solution to that issue is to change the Platform Target to 'Any CPU'.**

**Comment by ferib** [comment]
If the "32-bit process tries to access a 64-bit process and ..." is included it means that your build is set to 32bit, you can disable this at your solution properties under the tab 'Debug': 
![image](https://user-images.githubusercontent.com/22753171/114909142-1b0cdc80-9e1d-11eb-9e67-d47612d7b7b7.png)

**Comment by ferib** [comment]
@tgonzalez89 
> I tried reducing the delay before it patches and it now says it's done, but the game never launches.

I have added a _(temp)_ fix for the timing issue in commit https://github.com/ferib/D2R-Offline/commit/f8fff5e9c7456dffea989953469d3e4e4e6cdb41, try if it works!

**Comment by tgonzalez89** [comment]
I have those exact settings. Platform Target Any CPU and Prefer 32-bit unchecked. Still getting the same error. I even forced 64-bit in the platform target. When I force 32-bit I get this error: `Unhandled exception. System.ComponentModel.Win32Exception (299): A 32 bit processes cannot access modules of a 64 bit process.` For 64-bit the error is difference: `Unhandled exception. System.ComponentModel.Win32Exception (299): Only part of a ReadProcessMemory or WriteProcessMemory request was completed.`.

**Comment by tgonzalez89** [comment]
> 
> 
> @tgonzalez89
> 
> > I tried reducing the delay before it patches and it now says it's done, but the game never launches.
> 
> I have added a _(temp)_ fix for the timing issue in commit [f8fff5e](https://github.com/ferib/D2R-Offline/commit/f8fff5e9c7456dffea989953469d3e4e4e6cdb41), try if it works!


Same thing as when i reduced the Thread.Sleep. Runs, says done, but the game never launches.



[11:24:23.79032]: Launching game...
[11:24:23.85196]: Process started...
[11:24:24.25392]: Suspending process...
[11:24:24.27238]: Waiting for process exectuion...
[11:24:24.52596]: Process suspended
[11:24:24.52653]: Remapping process..
[11:24:24.59192]: Bypassed CRC at 7FF6A31554D0
[11:24:24.59260]: Bypassed CRC at 7FF6A3157430
[11:24:24.59444]: Bypassed CRC at 7FF6A3192F50
[11:24:24.59519]: Bypassed CRC at 7FF6A319EE80
[11:24:24.59566]: Bypassed CRC at 7FF6A319F550
[11:24:24.59844]: Bypassed CRC at 7FF6A32062B1
[11:24:24.60088]: Bypassed CRC at 7FF6A325D901
[11:24:24.66085]: Bypassed CRC at 7FF6A3CB58C0
[11:24:24.66129]: Bypassed CRC at 7FF6A3CB5DB0
[11:24:24.66194]: Bypassed CRC at 7FF6A3CC2251
[11:24:24.66232]: Bypassed CRC at 7FF6A3CC28D0
[11:24:24.69588]: Bypassed CRC at 7FF6A4288111
[11:24:24.71455]: Bypassed CRC at 7FF6A45BC501
[11:24:24.71560]: Bypassed CRC at 7FF6A45DCFD1
[11:24:24.71636]: Bypassed CRC at 7FF6A45EFC71
[11:24:24.71847]: Bypassed CRC at 7FF6A4607891
[11:24:24.71951]: Bypassed CRC at 7FF6A460F690
[11:24:24.72004]: Bypassed CRC at 7FF6A4615FC0
[11:24:24.72105]: Bypassed CRC at 7FF6A46323A0
[11:24:24.72167]: Bypassed CRC at 7FF6A463D9B1
[11:24:24.72226]: Bypassed CRC at 7FF6A4647DD1
[11:24:24.72328]: Bypassed CRC at 7FF6A4664791
[11:24:24.72457]: Bypassed CRC at 7FF6A468EA30
[11:24:24.72500]: Bypassed CRC at 7FF6A4692D31
[11:24:24.72561]: Bypassed CRC at 7FF6A469FB61
[11:24:24.72641]: Bypassed CRC at 7FF6A46B3930
[11:24:24.72697]: Bypassed CRC at 7FF6A46BC8F1
[11:24:24.72733]: Bypassed CRC at 7FF6A46BE981
[11:24:24.72806]: Bypassed CRC at 7FF6A46D02E0
[11:24:24.72848]: Bypassed CRC at 7FF6A46D42F0
[11:24:24.72901]: Bypassed CRC at 7FF6A46DCAE1
[11:24:24.72941]: Bypassed CRC at 7FF6A46E0771
[11:24:24.72979]: Bypassed CRC at 7FF6A46E3F81
[11:24:24.73012]: Bypassed CRC at 7FF6A46E5D71
[11:24:24.73093]: Bypassed CRC at 7FF6A46FAFF1
[11:24:24.73142]: Bypassed CRC at 7FF6A4700A50
[11:24:24.73265]: Bypassed CRC at 7FF6A47283B1
[11:24:24.73345]: Bypassed CRC at 7FF6A4738961
[11:24:24.78377]: Patching base+D4AD68
[11:24:24.78426]: Patching base+D4E25F
[11:24:24.78459]: Patching base+CAFB9D
[11:24:24.78493]: Patching base+597E1C
[11:24:24.78530]: Patching base+C5E81C
[11:24:24.78564]: Patching base+D615F2
[11:24:24.78596]: Patching base+39FC03
[11:24:24.78888]: Resuming process..
[11:24:24.78917]: Done!

**Comment by anta88** [comment]
> Same problem here, Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
> I have no standalone antivirus, just windows defender which I tried to disable. Any idea?

So, I deleted the D2R directory and re-downloaded the game with the tool BNetInstaller. Also on my first try, I used that tool, however, at the end of the download, battle.net updater asks to run. 
On the first try, I said yes, this time I said NO.

Afterward, the patching worked.

**Comment by Dankmank** [comment]
> 
> 
> Platform Target Any CPU and Prefer 32-bit unchecked. Still getting the same error. 

same here. is the folder location of the  D2 installation or the patcher important? I tried different variations but no difference..

**Comment by ferib** [comment]
in an attempt to fix this, have a look at the new `v2.0.0-beta` release: https://github.com/ferib/D2R-Offline/releases/tag/v2.0.0-beta
Keep me posted on how it goes!

**Comment by mfrklic** [comment]
> > Same problem here, Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
> > I have no standalone antivirus, just windows defender which I tried to disable. Any idea?
> 
> So, I deleted the D2R directory and re-downloaded the game with the tool BNetInstaller. Also on my first try, I used that tool, however, at the end of the download, battle.net updater asks to run.
> On the first try, I said yes, this time I said NO.
> 
> Afterward, the patching worked.

My brother had the same issue and redownload and saying no to the pop up seemed to resolved it. We also made sure to disable UAC the next time around before the download which may have helped as I had no issues and UAC always disabled.

**Comment by Kayzng** [comment]
got pretty much the same error
![d2rr](https://user-images.githubusercontent.com/82244594/114997425-6634f700-9ed2-11eb-92fe-e2f5bf771ee4.jpg)

**Comment by CDune23** [comment]
I had the same error - go into the launcher and verify game files, the error went away then. As for save files, you need to start a TCP/IP game to load saves. If it's greyed out, rename game.exe to something else and it should work.
